### ISSUE TITLE
Can't find parameter.json

### ISSUE THREAD

**Issue by choltz95** [Mishne-Lab/CIDAN#30]

**Comment by gadgetsam** [comment]
What do you mean by "path arg is a bit much"?

**Comment by choltz95** [comment]
> What do you mean by "path arg is a bit much"?

It's nothing important - I was trying to review a bunch of logged error messages, but the FileNotFoundError for the parameter.json was taking up a lot of space.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/CIDAN/GUI/Data_Interaction/DataHandler.py", line 335, in load_param_json
    with open(self.param_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './alwefjawef'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/CIDAN/__main__.py", line 55, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/CIDAN/__main__.py", line 42, in main
    load_into_mem=True)
  File "/usr/local/lib/python3.7/site-packages/CIDAN/GUI/Data_Interaction/DataHandler.py", line 153, in __init__
    valid = self.load_param_json()
  File "/usr/local/lib/python3.7/site-packages/CIDAN/GUI/Data_Interaction/DataHandler.py", line 351, in load_param_json
    raise FileNotFoundError("Can't find parameter file")
FileNotFoundError: Can't find parameter file
```
